services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: builder
    container_name: ${APP_NAME}-nextjs
    ports:
      - ${APP_HTTP_PORT}:3000
    volumes:
      - ./app:/app
